import { StaticImageData } from 'next/image';
import simon from './posters/simon.png';
import simonThumb from './thumbs/simon.jpg';

export interface hakflixShow {
	id: number;
	title: string;
	poster: StaticImageData;
	thumb: StaticImageData;
	cast: string;
	genres: string[];
	description: string;
}

const shows: hakflixShow[] = [
	{
		id: 1,
		title: 'Breaking HAK',
		poster: simon,
		thumb: simonThumb,
		cast: 'Felix Bischof',
		description: '',
		genres: ['Crime-Action', 'Abenteuer'],
	},
	{
		id: 2,
		title: 'TOP GUY',
		poster: simon,
		thumb: simonThumb,
		cast: 'Pascal Blank',
		description: '',
		genres: ['Dokumentationen', 'Action'],
	},
	{
		id: 3,
		title: 'Richard',
		poster: simon,
		thumb: simonThumb,
		cast: 'Richard Anton Brunner',
		description: '',
		genres: ['Science-Fiction'],
	},
	{
		id: 4,
		title: 'Burak Dogan is Klassensprecher',
		poster: simon,
		thumb: simonThumb,
		cast: 'Burak Dogan',
		description: '',
		genres: ['Stand-up-Comedy und Talkshows'],
	},
	{
		id: 5,
		title: 'AshabDhzamulaev',
		poster: simon,
		thumb: simonThumb,
		cast: 'Askhab Dhzamulaev',
		description: '',
		genres: ['Action', 'Thriller'],
	},
	{
		id: 6,
		title: 'Simon',
		poster: simon,
		thumb: simonThumb,
		cast: 'Simon Engl',
		description: '',
		genres: ['Action', 'Abenteuer'],
	},
	{
		id: 7,
		title: 'BENNI',
		poster: simon,
		thumb: simonThumb,
		cast: 'Benjamin Gärtner',
		description: '',
		genres: ['Thriller', 'Übernatürliche Horrorfilme'],
	},
	{
		id: 8,
		title: 'MAXIMILIAN',
		poster: simon,
		thumb: simonThumb,
		cast: 'Maximilian Grätz',
		description: '',
		genres: ['Comedyserien', 'Action'],
	},
	{
		id: 9,
		title: 'Der LAUFENDE TOD',
		poster: simon,
		thumb: simonThumb,
		cast: 'Noelle Hofstädter',
		description: '',
		genres: ['Horror', 'Action'],
	},
	{
		id: 10,
		title: 'TARIK KADRIC',
		poster: simon,
		thumb: simonThumb,
		cast: 'Tarik Kadric',
		description: '',
		genres: ['Action-Thriller'],
	},
	{
		id: 11,
		title: 'Annika With A "NN"',
		poster: simon,
		thumb: simonThumb,
		cast: 'Annika King',
		description: '',
		genres: ['Tiergeschichten', 'Familienabenteuer'],
	},
	{
		id: 12,
		title: 'JOHANNES',
		poster: simon,
		thumb: simonThumb,
		cast: 'Johannes Lohs',
		description: '',
		genres: ['Italienisch', 'Psychothriller'],
	},
	{
		id: 13,
		title: 'Better call Justin!',
		poster: simon,
		thumb: simonThumb,
		cast: 'Justin Martan',
		description: '',
		genres: ['Comedyserie'],
	},
	{
		id: 14,
		title: 'PATRICK MÜLLER',
		poster: simon,
		thumb: simonThumb,
		cast: 'Patrick Müller',
		description: '',
		genres: ['Horror', 'Thriller'],
	},
	{
		id: 15,
		title: 'LEON PILICIC',
		poster: simon,
		thumb: simonThumb,
		cast: 'Leon Pilicic',
		description: '',
		genres: ['Action', 'Thriller'],
	},
	{
		id: 16,
		title: 'MARKUS',
		poster: simon,
		thumb: simonThumb,
		cast: 'Markus Reis',
		description: '',
		genres: ['Stand-up-Comedy', 'Für Kinder'],
	},
	{
		id: 17,
		title: 'Most Wanted Man',
		poster: simon,
		thumb: simonThumb,
		cast: 'Arda Sahin',
		description: '',
		genres: ['Action', 'Satiren'],
	},
	{
		id: 18,
		title: 'SHE',
		poster: simon,
		thumb: simonThumb,
		cast: 'Hannah Scheidbach',
		description: '',
		genres: ['Horror'],
	},
	{
		id: 19,
		title: "Anika's Schneider",
		poster: simon,
		thumb: simonThumb,
		cast: 'Anika Schneider',
		description: '',
		genres: ['Mystery', 'Romantische Dramen'],
	},
	{
		id: 20,
		title: 'MONDAY',
		poster: simon,
		thumb: simonThumb,
		cast: 'Leonie Wagner',
		description: '',
		genres: ['Übernatürliche Horrofilme'],
	},
	{
		id: 21,
		title: "Melanie's Moving Castle",
		poster: simon,
		thumb: simonThumb,
		cast: 'Melanie Wolf',
		description: '',
		genres: ['Anime', 'Fantasy-Filme'],
	},
];

export default shows;
